# The workflow name appears on any pull request or in the Actions tab of your repository.
# indicates that your workflow will execute anytime a pull request opens in your repository.
name: Post welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
      # post a comment on the pull request using a bash script and GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
